### ISSUE TITLE
windows 环境, 安装包问题

### ISSUE THREAD

**Issue by digger-yu** [ibaihuo/chanvis#3]
```
error D:\git\chanvis\ui\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: D:\git\chanvis\ui\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe D:\git\chanvis\ui\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\git\\chanvis\\ui\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@20.12.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\git\chanvis\ui\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\git\chanvis\ui\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\git\chanvis\ui\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\git\chanvis\ui\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\git\chanvis\ui\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\git\chanvis\ui\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:204:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\git\chanvis\ui\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\git\chanvis\ui\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\git\chanvis\ui\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\git\chanvis\ui\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\git\chanvis\ui\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\git\chanvis\ui\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:204:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Program Files\python3.10.11\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\python3.10.11\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
gyp ERR! stack
gyp ERR! stack     at genericNodeError (node:internal/errors:984:15)
gyp ERR! stack     at wrappedFn (node:internal/errors:538:14)
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:422:12)
gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\git\\chanvis\\ui\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\git\chanvis\ui\node_modules\node-sass
gyp ERR! node -v v20.12.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok


PS D:\git\chanvis\ui>
PS D:\git\chanvis\ui> npm -v
10.5.0
PS D:\git\chanvis\ui> yarn -v
1.22.22
PS D:\git\chanvis\ui> python --version
Python 3.10.11
PS D:\git\chanvis\ui>
```

请帮忙看看

**Comment by dzmjs** [comment]
You need to copy a DIR.
https://github.com/tradingview/charting-library-examples/blob/master/vuejs/README.md
From this website, you can see that the author copy a Vue2 dir from <tradingview/charting-library-examples>
However the [charting_library/](https://github.com/tradingview/charting_library/) is NOT exist now.

**Comment by dzmjs** [comment]
https://github.com/gaoming13/tradingview
In this website, you can see the ZIP format file. Yes, it is the correct ZIP file. I have validated the file in this project.

**Comment by digger-yu** [comment]
> https://github.com/gaoming13/tradingview In this website, you can see the ZIP format file. Yes, it is the correct ZIP file. I have validated the file in this project.

hi 请问是复制压缩文件的全部内容到public目录还是仅仅复制压缩文件中的charting_library 子目录下的内容到public目录下
~~~
├─.github
│  └─ISSUE_TEMPLATE
├─charting_library
│  └─static
│      ├─bundles
│      ├─fonts
│      ├─images
│      │  ├─charting_library
│      │  ├─dialogs
│      │  ├─sidetoolbar
│      │  └─svg
│      │      └─chart
│      └─lib
│          └─external
└─datafeeds
    └─udf
        ├─dist
        ├─lib
        └─src
~~~
两种我都试过， 还是报同样的错误

**Comment by trevortongxy** [comment]
> https://github.com/gaoming13/tradingview In this website, you can see the ZIP format file. Yes, it is the correct ZIP file. I have validated the file in this project.

some packages are out of date
